version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: razor-blade-backend
    environment:
      - RAZOR_BLADE_SERVER_PORT=8080
      - RAZOR_BLADE_SERVER_MODE=release
      - RAZOR_BLADE_DATABASE_PATH=/app/data/razor-blade.db
      - RAZOR_BLADE_LOG_LEVEL=info
      - RAZOR_BLADE_LOG_FORMAT=json
    volumes:
      - backend_data:/app/data
    networks:
      - razor-blade-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: razor-blade-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - razor-blade-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local

networks:
  razor-blade-network:
    driver: bridge