server:
  port: "8080"
  mode: "debug"  # debug, release, test

database:
  path: "./data/razor-blade.db"  # 开发环境使用文件数据库

log:
  level: "info"  # debug, info, warn, error
  format: "text" # text, json